backend:
  name: git-gateway
  branch: main

media_folder: "_site/posts"
public_folder: "/posts"
collections:
  - name: "posts"
    label: "Posts"
    folder: "/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "string", default: "posts.html" }
      - { label: "Ort", name: "ort", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "markdown" }
      - { label: "Postleitzahl", name: "plz", widget: "string" }
      - { label: "Vorschaubild", name: "preview-image", widget: "image" }
      - { label: "Bilder Detailansicht", name: "images", widget: "image" }
